language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - npm install

script:
  - grunt build
  - "cd dist/workflow && PYTHONPATH=. py.test ../../tests --cov-report term-missing --cov mstodo"

after_success:
  - coveralls