"""
Generated by `codellama/CodeLlama-70b-Instruct-hf`
Prompt: Help me to write a Pydantic model class, allowing converting this json to Python object:
{
    'id': '<task_folder_id>',
    'changeKey': '<changekey>',
    'name': 'task',
    'isDefaultFolder': True,
    'parentGroupKey': '<UUID>'
}
"""
from __future__ import annotations
from typing import Any, Dict, Union
from uuid import UUID
from pydantic import BaseModel, Field


class TaskFolder(BaseModel):
    id: UUID = Field(..., description="Unique Identifier.")
    change_key: bytes = Field(..., min_length=24, max_length=24, description="Change Key.")
    name: str = Field(..., description="Name of the Folder.")
    is_default_folder: bool = Field(..., description="Indicates if its Default Folder.")
    parent_group_key: UUID = Field(..., description="Parent Group Key.")

    @property
    def dict(self) -> Dict[str, Any]:
        return self.__dict__.copy()

    @staticmethod
    def load(obj: Union[Dict[Any, Any]]) -> TaskFolder:
        try:
            instance = TaskFolder(**obj)
        except Exception as e:
            raise ValueError(f"Invalid Object Format.\n{e}")
        return instance
